### ISSUE TITLE
SoapClient : request walletsale problem

### ISSUE THREAD

**Issue by SivaPsr** [rojobo/TransactionExpressPHP#2]
Am using php5.6 win:8.1

Unable to make wallet sale through SOAP client.

My request array like

    `(
    [reqAmt] => 025000
    [recurMan] => Array
        (
            [id] => 1537444446788162467
        )

    [merc] => Array
        (
            [id] => 7777778541
            [regKey] => P7BAZYW45B9FA94F
            [inType] => 1
            [prodType] => 5
        )

    [tranCode] => 0
)`

But last sent request printed 
     `<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://postilion/realtime/merchantframework/xsd/v1/"><SOAP-ENV:Body><ns1:SendTranRequest><ns1:merc><ns1:id>12345678</ns1:id><ns1:regKey>1231ewre123132</ns1:regKey><ns1:inType>1</ns1:inType><ns1:prodType>5</ns1:prodType></ns1:merc><ns1:tranCode>0</ns1:tranCode><ns1:reqAmt>025000</ns1:reqAmt><ns1:recurMan><ns1:id>2147483647</ns1:id></ns1:recurMan></ns1:SendTranRequest></SOAP-ENV:Body></SOAP-ENV:Envelope>`

If I convert float before sent request then wallet id changed 
  sent id   1537444446788162467  
  But: sent recurMan is 1537444446788162560

How to resolve it ?

**Comment by rojobo** [comment]
I think it needs to be a string value because the numeric representtion is greater than 32 bit, have you looked at the reference guide provided by tranunion?
